codenvy/user-dashboard

app/partials/widgets/importGitHub.html
app/scripts/directives/import-github.js
app/styles/main.css

Bugfixes and improvements around project import

Rework import

---

app/index.html
app/scripts/app.js
app/styles/codemirror.css
app/styles/main.css
bower.json

* Default global options (linenumber, linewrapping, theme, add-
ons),
* Syntax checking with JSLint,
* Code folding,
* Brackets matching and autoclosing,
* Active line highlighting,
* Editor theming.

UD-262 Improve CodeMirror integration in UD

---

app/scripts/controllers/dashboard.js
app/views/dashboard.html

Remove the alternate view displaying projects in list instead of boxes.

Fix UD-296 Remove list view for projects

---

app/styles/main.css
app/views/dashboard.html

Restore the previous big import button instead of the three ones
introduced.

Fix UD-308 Replace 4 import buttons by only one

---

app/partials/templates/projects/confirmGitHubOAuthPopUp.html
app/partials/widgets/importGitHub.html
app/scripts/directives/import-github.js

* Prevent blocking of the pop-up window by requering expliciti click
action of the user to trigger the opening,
* Globaly improve GitHub authentication success and failure handling.

Fix UD-321 Pop-up blocker blocks GitHub OAuth window

---

app/partials/templates/projects/newProjectModal.html
app/scripts/controllers/newProject.js

Make the import synchronous (dialog is not closed upon clicking on
import button) and display success or error messages.

Fix UD-325 Synchronous import and errors report

---

app/index.html
app/partials/templates/factories/deleteFactoryModal.html
app/partials/templates/factories/newFactoryModal.html
app/partials/templates/factories/shareFactoryModal.html
app/partials/widgets/newFactoryFromFile.html
app/scripts/app.js
app/scripts/controllers/factories.js
app/scripts/controllers/factory.js
app/scripts/controllers/navbar.js
app/scripts/directives/new-factory-from-file.js
app/scripts/services/new-factory.js
app/styles/main.css
app/views/factories.html
app/views/factorydetails.html
bower.json

Ability to create/update/delete a factory

UD-92 Add factory tab on user dashboard

---

app/partials/templates/projects/newProjectModal.html
app/partials/widgets/importGitHub.html
app/partials/widgets/importGitRepository.html
app/partials/widgets/importZip.html
app/partials/widgets/newProjectDetails.html
app/scripts/controllers/newProject.js
app/scripts/directives/import-git-repository.js
app/scripts/directives/import-github.js
app/scripts/directives/import-zip.js
app/scripts/directives/new-project-details.js
app/styles/main.css

Add required fields in dialog modal and disabled import button
accordingly.

Fix UD-305 Validation on import dialog fields

---

app/index.html
app/partials/templates/projects/newProjectModal.html
app/partials/widgets/importFactory.html
app/partials/widgets/importGitHub.html
app/partials/widgets/importGitRepository.html
app/partials/widgets/importZip.html
app/partials/widgets/newProjectDetails.html
app/scripts/app.js
app/scripts/controllers/newProject.js
app/scripts/directives/import-factory.js
app/scripts/directives/import-git-repository.js
app/scripts/directives/import-github.js
app/scripts/directives/import-zip.js
app/scripts/directives/new-factory-from-file.js
app/scripts/directives/new-project-details.js
app/styles/main.css

Add import from config to be able to import from a JSON config and
enable two way binding between JSON and fields. Codemirror validation
state is also taken into account on Import button disable/enable state.

Fix UD-262 Add import from config tab

---

app/scripts/app.js
app/scripts/directives/import-factory.js

* end of app.js indent fixing,
* remove debug logs in import-factory.js.

Fix UD-262 Fix little quirks of #58bc2a

---

app/scripts/controllers/dashboard.js
app/views/dashboard.html

* Remove again layout toggling button,
* Fix filter by workspace: set filter and reenable get projects on all
workspaces.

Fix UD-296 Fix regressions by UD-290

---

app/index.html
app/scripts/app.js
app/scripts/directives/import-github.js
app/scripts/services/git-hub-rest-service.js
bower.json

* Evolution to target new upcoming GitHub API version,
* Automatic unpagination of results.

Fix UD 327 Improve GitHub API consumption

---

app/index.html
app/partials/widgets/importGitRepository.html
app/partials/widgets/importZip.html
app/partials/widgets/newProjectDetails.html
app/scripts/directives/import-git-repository.js
app/scripts/directives/remote-url.validator.js

Fix UD-344 Validate Git URL format

---

src/app/dashboard/dashboard.html
src/app/factories/list-factories/factories.html
src/app/projects/create-project/create-project.html
src/app/projects/list-projects/list-projects.html
src/app/projects/project-details/project-details.controller.js
src/app/projects/project-details/project-details.html
src/components/widget/button/cdvy-button-primary.directive.js
src/components/widget/toolbar/toolbar.directive.js
src/components/widget/toolbar/toolbar.styl

Allow to customize breadcrumb, title icons (as many as we want + callback), and subheader

UD-428 Complete page-header component

---

app/account/AccountService.js
app/account/billing/BillingController.js
app/account/billing/billing.html
app/account/subscription/SubscriptionController.js
app/account/subscription/subscriptions.html

UD-550: Added Monthly Fee and Monthly Prepaid fields

---

src/app/colors/codenvy-colors.json
src/app/colors/codenvy-colors.styl
src/app/countries/codenvy-countries.constant.js
src/app/index.js
src/app/navbar/account/account.controller.js
src/app/navbar/account/account.html
src/app/navbar/account/profile/account-profile.controller.js
src/app/navbar/account/profile/account-profile.html
src/app/navbar/navbar.controller.js
src/app/navbar/navbar.html
src/app/navbar/navbar.styl
src/app/projects/project-details/project-details.controller.js
src/app/projects/project-details/project-details.html
src/components/api/codenvy-profile.factory.js
src/components/api/codenvy-profile.spec.js
src/components/api/test/codenvy-http-backend.js
src/components/widget/input/cdvy-input.html
src/components/widget/select/cdvy-select.directive.js
src/components/widget/select/cdvy-select.html
src/components/widget/select/cdvy-select.styl
src/components/widget/widget-config.js

UD-498: Add select widget and API to manage profile information

---

app/account/billing/BillingController.js

To be merged when ready for 3.9.6

UD-570: Update free gbh from 10 to 20

---

bower.json
src/app/index.js
src/app/navbar/account/account-config.js
src/app/navbar/account/account-delete.controller.js
src/app/navbar/account/account-delete.directive.js
src/app/navbar/account/account-delete.html
src/app/navbar/account/account-delete.styl
src/app/navbar/account/account-update-password.directive.js
src/app/navbar/account/account-update-password.html
src/app/navbar/account/account-update-password.styl
src/app/navbar/account/account.controller.js
src/app/navbar/account/account.html
src/app/navbar/account/account.styl
src/app/navbar/account/profile/account-profile.html
src/app/navbar/navbar-config.js
src/components/api/codenvy-user.factory.js
src/components/api/codenvy-user.spec.js
src/components/api/test/codenvy-http-backend.js
src/components/notification/codenvy-notification-info.html
src/components/notification/codenvy-notification.styl
src/components/widget/input/cdvy-input.styl
src/components/widget/select/cdvy-select.directive.js
src/components/widget/select/cdvy-select.styl
src/index.html

UD-500: Added security view for password management

---

src/app/onpremises/admin/bridge/account/account.controller.js
src/app/onpremises/admin/bridge/account/account.html
src/app/onpremises/admin/bridge/software/software.html
src/app/onpremises/admin/bridge/software/software.styl
src/app/onpremises/admin/bridge/yoursubscription/yoursubscription.controller.js
src/app/onpremises/admin/bridge/yoursubscription/yoursubscription.html
src/app/onpremises/admin/bridge/yoursubscription/yoursubscription.styl
src/app/onpremises/admin/installation/upgrade/upgrade.controller.js
src/app/onpremises/admin/installation/upgrade/upgrade.html
src/app/onpremises/admin/installation/yourinstall/yourinstall.html
src/app/onpremises/admin/installation/yourinstall/yourintall.styl
src/components/ims/ims-artifact.factory.js
src/components/widget/link/cdvy-link.directive.js
src/components/widget/link/cdvy-link.styl
src/components/widget/panel/cdvy-panel.styl

Mostly styling.
Subscription and artifact logic.

Pack of unrelated changes

---

bower.json
src/components/widget/button/cdvy-button.directive.js
src/components/widget/input/cdvy-input.directive.js
src/index.html

Only the input and button elements have a positive tabindex.
cdvy-button properly handles ngDisabled.

Component tabindex + cdvy-button ngDisabled

---

src/app/projects/project-details/project-details.html
src/app/projects/project-details/repository/project-repository-config.js
src/app/projects/project-details/repository/project-repository.controller.js
src/app/projects/project-details/repository/project-repository.directive.js
src/app/projects/project-details/repository/project-repository.html
src/app/projects/project-details/repository/project-repository.styl
src/app/projects/projects-config.js
src/components/api/codenvy-api.factory.js
src/components/api/codenvy-git.factory.js
src/components/api/codenvy-git.spec.js
src/components/api/test/codenvy-http-backend.js
src/components/widget/label/cdvy-label.html
src/components/widget/label/cdvy-label.styl

UD-418: Added widget with repository information for current project

---

src/app/onpremises/admin/bridge/account/account.controller.js
src/app/onpremises/admin/bridge/account/account.html
src/app/onpremises/admin/installation/automatic/automatic.controller.js

Use a form for the login part (allows to submit on ENTER)
Move the 30 days subscription advertisement at the bottom

Account form

---

e2e/projects/project-details/rename-project/rename-project-http.mock.js
src/app/navbar/navbar.styl
src/app/projects/project-details/project-details.controller.js
src/app/projects/project-details/repository/project-repository-data.js
src/app/projects/project-details/repository/project-repository.controller.js
src/app/projects/project-details/repository/project-repository.html
src/app/projects/project-details/repository/project-repository.styl
src/components/api/codenvy-api.factory.js
src/components/api/codenvy-git.factory.js
src/components/api/codenvy-git.spec.js
src/components/api/codenvy-project.factory.js
src/components/api/codenvy-project.spec.js
src/components/api/codenvy-svn.factory.js
src/components/api/codenvy-svn.spec.js
src/components/api/test/codenvy-http-backend.js

UD-418: Added svn support

---

e2e/projects/project-details/permissions/project-details-permissions.po.js
e2e/projects/project-details/rename-project/rename-project-http.mock.js
e2e/projects/project-details/rename-project/rename-project.po.js
e2e/projects/project-details/rename-project/rename-project.spec.js
protractor.conf.js
src/app/projects/project-details/project-details.controller.js
src/app/projects/project-details/repository/project-repository-data.js
src/app/projects/project-details/repository/project-repository.controller.js
src/app/projects/project-details/repository/project-repository.html
src/app/projects/project-details/repository/project-repository.styl
src/components/api/codenvy-git.spec.js
src/components/api/test/codenvy-http-backend.js
src/components/widget/empty-repository/cdvy-empty-repository.directive.js
src/components/widget/empty-repository/cdvy-empty-repository.html
src/components/widget/empty-repository/cdvy-empty-repository.styl
src/components/widget/toolbar/toolbar.styl
src/components/widget/widget-config.js

UD-578: Added empty state widget

---

src/app/projects/project-details/repository/project-repository.html

Code clean up

---

bower.json
src/app/index.js
src/app/projects/list-projects/list-projects.controller.js
src/app/projects/list-projects/list-projects.html
src/app/projects/list-projects/list-projects.styl
src/components/widget/copy-clipboard/cdvy-clipboard.directive.js
src/components/widget/copy-clipboard/cdvy-clipboard.styl
src/components/widget/tab/cdvy-tab.directive.js
src/components/widget/tooltip/cdvy-tooltip.directive.js
src/components/widget/tooltip/cdvy-tooltip.html
src/components/widget/tooltip/cdvy-tooltip.styl
src/components/widget/widget-config.js

UD-543: Added missing tooltips

---

src/app/index.styl
src/app/projects/list-projects/list-projects.html
src/app/projects/list-projects/list-projects.styl
src/components/widget/search/cdvy-search.styl
src/components/widget/toolbar/toolbar.directive.js
src/components/widget/toolbar/toolbar.styl

UD-546: Fixed design for small screen
